app = "terrenkur-bot"
primary_region = "ams"

[build]
  dockerfile = "bot/Dockerfile"

[processes]
  app = "npm start"

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  processes = ["app"]        # ← добавлено!
  auto_stop_machines = "off" # держать всегда запущенной
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    path = "/health"
    interval = "15s"
    timeout = "2s"
    method = "get"
