app = "terrenkur-bot"
primary_region = "ams"

[build]
  dockerfile = "bot/Dockerfile"

[processes]
  app = "npm start"

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  # Ключевые строки ↓
  auto_stop_machines = "off"   # НЕ останавливать машины
  auto_start_machines = false  # автозапуск от трафика не нужен
  min_machines_running = 1     # держать минимум 1 машину

  [[http_service.checks]]
    path = "/health"
    interval = "15s"
    timeout = "2s"
    method = "get"

