app = "terrenkur-bot"
primary_region = "ams"

[build]
  dockerfile = "bot/Dockerfile"

[processes]
  app = "npm start"

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 3000

  [[http_service.checks]]
    path = "/health"
    interval = "15s"
    timeout = "2s"
    method = "get"
