module.exports = {
  clipSuccess: 'SB_CHAT_CLIP',
  clipError: 'SB_CHAT_CLIP_ERROR',
  intimResult: 'SB_CHAT_INTIM',
  intimNoParticipants: 'SB_CHAT_INTIM_NO_PARTICIPANTS',
  poceluyResult: 'SB_CHAT_POCELUY',
  poceluyNoParticipants: 'SB_CHAT_POCELUY_NO_PARTICIPANTS',
  rewardExtraVote: 'SB_CHAT_REWARD_EXTRA_VOTE',
  musicQueued: 'SB_CHAT_REWARD_MUSIC_ENQUEUED',
  musicInvalidLink: 'SB_CHAT_REWARD_INVALID_MUSIC_LINK',
  pollHelp: 'SB_CHAT_POLL_HELP',
  pollNoActive: 'SB_CHAT_POLL_NO_ACTIVE',
  pollList: 'SB_CHAT_POLL_LIST',
  pollListError: 'SB_CHAT_POLL_LIST_ERROR',
  pollVotesStatus: 'SB_CHAT_POLL_VOTES_STATUS',
  pollVotesError: 'SB_CHAT_POLL_VOTES_ERROR',
  pollVotingClosed: 'SB_CHAT_POLL_VOTING_CLOSED',
  pollGameNotFound: 'SB_CHAT_POLL_GAME_NOT_FOUND',
  pollVoteSuccess: 'SB_CHAT_POLL_VOTE_SUCCESS',
  pollVoteLimit: 'SB_CHAT_POLL_VOTE_LIMIT',
  pollVoteTechnical: 'SB_CHAT_POLL_VOTE_TECHNICAL',
  pollVoteProcessingError: 'SB_CHAT_POLL_VOTE_PROCESSING_ERROR',
  whereResult: 'SB_CHAT_WHERE_RESULT',
  whenResult: 'SB_CHAT_WHEN_RESULT',
  whereToResult: 'SB_CHAT_WHERE_TO_RESULT',
  whatResult: 'SB_CHAT_WHAT_RESULT',
  whoResult: 'SB_CHAT_WHO_RESULT',
};
