alter table users
  add column if not exists poceluy_no_tag_0 integer default 0,
  add column if not exists poceluy_no_tag_69 integer default 0,
  add column if not exists poceluy_no_tag_100 integer default 0,
  add column if not exists poceluy_with_tag_0 integer default 0,
  add column if not exists poceluy_with_tag_69 integer default 0,
  add column if not exists poceluy_with_tag_100 integer default 0,
  add column if not exists poceluy_self_no_tag integer default 0,
  add column if not exists poceluy_self_no_tag_0 integer default 0,
  add column if not exists poceluy_self_no_tag_69 integer default 0,
  add column if not exists poceluy_self_no_tag_100 integer default 0,
  add column if not exists poceluy_self_with_tag integer default 0,
  add column if not exists poceluy_self_with_tag_0 integer default 0,
  add column if not exists poceluy_self_with_tag_69 integer default 0,
  add column if not exists poceluy_self_with_tag_100 integer default 0,
  add column if not exists poceluy_tagged_equals_partner integer default 0,
  add column if not exists poceluy_tagged_equals_partner_0 integer default 0,
  add column if not exists poceluy_tagged_equals_partner_69 integer default 0,
  add column if not exists poceluy_tagged_equals_partner_100 integer default 0,
  add column if not exists poceluy_tag_match_success integer default 0,
  add column if not exists poceluy_tag_match_success_0 integer default 0,
  add column if not exists poceluy_tag_match_success_69 integer default 0,
  add column if not exists poceluy_tag_match_success_100 integer default 0;

